// Generated by Cadence Genus(TM) Synthesis Solution 23.13-s073_1
// Generated on: Apr  1 2026 13:08:18 IST (Apr  1 2026 07:38:18 UTC)

// Verification Directory fv/counter 

module counter(clk, rst, count, SE, scan_in, scan_out);
  input clk, rst, SE, scan_in;
  output [7:0] count;
  output scan_out;
  wire clk, rst, SE, scan_in;
  wire [7:0] count;
  wire scan_out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13;
  SDFFRHQX1 \count_reg[7] (.RN (rst), .CK (clk), .D (n_13), .SI
       (count[6]), .SE (SE), .Q (count[7]));
  SDFFRHQX1 \count_reg[6] (.RN (rst), .CK (clk), .D (n_12), .SI
       (count[5]), .SE (SE), .Q (count[6]));
  CLKXOR2X1 g184__2398(.A (count[7]), .B (n_11), .Y (n_13));
  ADDHX1 g186__5107(.A (count[6]), .B (n_9), .CO (n_11), .S (n_12));
  SDFFRHQX1 \count_reg[5] (.RN (rst), .CK (clk), .D (n_10), .SI
       (count[4]), .SE (SE), .Q (count[5]));
  ADDHX1 g188__6260(.A (count[5]), .B (n_7), .CO (n_9), .S (n_10));
  SDFFRHQX1 \count_reg[4] (.RN (rst), .CK (clk), .D (n_8), .SI
       (count[3]), .SE (SE), .Q (count[4]));
  ADDHX1 g190__4319(.A (count[4]), .B (n_5), .CO (n_7), .S (n_8));
  SDFFRHQX1 \count_reg[3] (.RN (rst), .CK (clk), .D (n_6), .SI
       (count[2]), .SE (SE), .Q (count[3]));
  ADDHX1 g192__8428(.A (count[3]), .B (n_3), .CO (n_5), .S (n_6));
  SDFFRHQX1 \count_reg[2] (.RN (rst), .CK (clk), .D (n_4), .SI
       (count[1]), .SE (SE), .Q (count[2]));
  ADDHX1 g194__5526(.A (count[2]), .B (n_1), .CO (n_3), .S (n_4));
  SDFFRHQX1 \count_reg[1] (.RN (rst), .CK (clk), .D (n_2), .SI
       (count[0]), .SE (SE), .Q (count[1]));
  SDFFRHQX1 \count_reg[0] (.RN (rst), .CK (clk), .D (n_0), .SI
       (scan_in), .SE (SE), .Q (count[0]));
  ADDHX1 g196__6783(.A (count[1]), .B (count[0]), .CO (n_1), .S (n_2));
  INVX1 g198(.A (count[0]), .Y (n_0));
  BUFX20 rm_assigns_buf_scan_out(.A (count[7]), .Y (scan_out));
endmodule

