
// Generated by Cadence Genus(TM) Synthesis Solution 23.13-s073_1
// Generated on: Sep 29 2025 05:26:39 IST (Sep 28 2025 23:56:39 UTC)

// Verification Directory fv/mag 

module mag(a, b, l_t, g_t, equ);
  input [3:0] a, b;
  output l_t, g_t, equ;
  wire [3:0] a, b;
  wire l_t, g_t, equ;
  wire n_2, n_5, n_6, n_7, n_9, n_10, n_11, n_14;
  wire n_15, n_16, n_18, n_32, n_33, n_34, n_35;
  NOR2BXL g563__5107(.AN (n_32), .B (n_18), .Y (equ));
  OAI31XL g564__6260(.A0 (n_35), .A1 (n_33), .A2 (n_14), .B0 (n_15), .Y
       (l_t));
  OR4X1 g565__4319(.A (n_33), .B (n_34), .C (n_11), .D (n_16), .Y
       (n_18));
  OAI211XL g566__8428(.A0 (b[0]), .A1 (n_2), .B0 (n_9), .C0 (n_15), .Y
       (n_16));
  OA21X1 g567__5526(.A0 (n_34), .A1 (n_32), .B0 (n_10), .Y (n_14));
  INVXL g568(.A (n_10), .Y (n_11));
  OA22X1 g569__6783(.A0 (a[1]), .A1 (n_6), .B0 (a[2]), .B1 (n_7), .Y
       (n_10));
  INVXL g572(.A (n_35), .Y (n_9));
  OR2X1 g574__1705(.A (a[3]), .B (n_5), .Y (n_15));
  INVXL g579(.A (a[0]), .Y (n_2));
  INVXL g582(.A (b[1]), .Y (n_6));
  INVXL g578(.A (b[2]), .Y (n_7));
  INVXL g583(.A (b[3]), .Y (n_5));
  NOR2X8 g2(.A (equ), .B (l_t), .Y (g_t));
  NAND2BX4 g584(.AN (a[0]), .B (b[0]), .Y (n_32));
  CLKAND2X12 g585(.A (n_7), .B (a[2]), .Y (n_33));
  CLKAND2X12 g586(.A (n_6), .B (a[1]), .Y (n_34));
  CLKAND2X12 g587(.A (n_5), .B (a[3]), .Y (n_35));
endmodule

