
// Generated by Cadence Genus(TM) Synthesis Solution 23.13-s073_1
// Generated on: Mar 26 2026 22:36:47 IST (Mar 26 2026 17:06:47 UTC)

// Verification Directory fv/counter 

module counter(clk, rst, count);
  input clk, rst;
  output [7:0] count;
  wire clk, rst;
  wire [7:0] count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13;
  SDFFRHQX1 \count_reg[7] (.RN (rst), .CK (clk), .D (n_12), .SE
       (count[7]), .SI (n_13), .Q (count[7]));
  DFFRHQX2 \count_reg[6] (.RN (rst), .CK (clk), .D (n_11), .Q
       (count[6]));
  INVX1 g185(.A (n_12), .Y (n_13));
  ADDHXL g186__2398(.A (count[6]), .B (n_9), .CO (n_12), .S (n_11));
  DFFRHQX2 \count_reg[5] (.RN (rst), .CK (clk), .D (n_10), .Q
       (count[5]));
  ADDHXL g188__5107(.A (count[5]), .B (n_7), .CO (n_9), .S (n_10));
  DFFRHQX2 \count_reg[4] (.RN (rst), .CK (clk), .D (n_8), .Q
       (count[4]));
  ADDHXL g190__6260(.A (count[4]), .B (n_5), .CO (n_7), .S (n_8));
  DFFRHQX2 \count_reg[3] (.RN (rst), .CK (clk), .D (n_6), .Q
       (count[3]));
  ADDHXL g192__4319(.A (count[3]), .B (n_3), .CO (n_5), .S (n_6));
  DFFRHQX2 \count_reg[2] (.RN (rst), .CK (clk), .D (n_4), .Q
       (count[2]));
  ADDHXL g194__8428(.A (count[2]), .B (n_1), .CO (n_3), .S (n_4));
  DFFRHQX2 \count_reg[1] (.RN (rst), .CK (clk), .D (n_2), .Q
       (count[1]));
  ADDHXL g196__5526(.A (count[1]), .B (count[0]), .CO (n_1), .S (n_2));
  DFFRX2 \count_reg[0] (.RN (rst), .CK (clk), .D (n_0), .Q (count[0]),
       .QN (n_0));
endmodule

