
// Generated by Cadence Genus(TM) Synthesis Solution 23.13-s073_1
// Generated on: Sep 28 2025 16:53:00 IST (Sep 28 2025 11:23:00 UTC)

// Verification Directory fv/demux 

module demux(in, s, y1, y2, y3, y4);
  input in;
  input [1:0] s;
  output y1, y2, y3, y4;
  wire in;
  wire [1:0] s;
  wire y1, y2, y3, y4;
  wire n_0, n_1, n_4;
  NOR3X1 g105__2398(.A (s[1]), .B (s[0]), .C (n_4), .Y (y1));
  NOR3X1 g107__5107(.A (s[1]), .B (n_4), .C (n_1), .Y (y2));
  NOR2X1 g108__6260(.A (s[0]), .B (n_0), .Y (y3));
  NOR2X1 g106__4319(.A (n_1), .B (n_0), .Y (y4));
  NAND2X8 g109__8428(.A (s[1]), .B (in), .Y (n_0));
  CLKINVX16 g110(.A (in), .Y (n_4));
  CLKINVX16 g111(.A (s[0]), .Y (n_1));
endmodule

