
// Generated by Cadence Genus(TM) Synthesis Solution 23.13-s073_1
// Generated on: Sep 28 2025 20:59:46 IST (Sep 28 2025 15:29:46 UTC)

// Verification Directory fv/full_adder 

module full_adder(a, b, c, sum, carry);
  input a, b, c;
  output sum, carry;
  wire a, b, c;
  wire sum, carry;
  ADDFX4 g2(.A (b), .B (a), .CI (c), .CO (carry), .S (sum));
endmodule

