
// Generated by Cadence Genus(TM) Synthesis Solution 23.13-s073_1
// Generated on: Apr 11 2026 21:19:02 IST (Apr 11 2026 15:49:02 UTC)

// Verification Directory fv/alu 

module alu(clk, rst_n, en, A, B, op_code, result_out, flag_carry,
     flag_zero);
  input clk, rst_n, en;
  input [7:0] A, B;
  input [2:0] op_code;
  output [7:0] result_out;
  output flag_carry, flag_zero;
  wire clk, rst_n, en;
  wire [7:0] A, B;
  wire [2:0] op_code;
  wire [7:0] result_out;
  wire flag_carry, flag_zero;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_19, n_21, n_23, n_24, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_48, n_49, n_50, n_51, n_52, n_53;
  wire n_54, n_55, n_56, n_57, n_58, n_59, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_90, n_92, n_93, n_94, n_95, n_96, n_97, n_98;
  wire n_99, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_122, n_123;
  wire n_124, n_125, n_126, n_127, n_128, n_129, n_130, n_131;
  wire n_132, n_133, n_134, n_135, n_136, n_137, n_138, n_139;
  wire n_140, n_141, n_142, n_191, n_192, n_193, n_194, n_195;
  wire n_196;
  DFFHQX1 flag_carry_reg(.CK (clk), .D (n_142), .Q (flag_carry));
  OAI21X1 g4517__2398(.A0 (n_83), .A1 (n_141), .B0 (n_101), .Y (n_142));
  DFFHQX1 \result_out_reg[7] (.CK (clk), .D (n_140), .Q
       (result_out[7]));
  XNOR2X1 g4520__5107(.A (n_73), .B (n_138), .Y (n_141));
  OAI2BB1X1 g4519__6260(.A0N (n_136), .A1N (n_139), .B0 (n_96), .Y
       (n_140));
  ADDFX1 g4521__4319(.A (A[7]), .B (n_88), .CI (n_134), .CO (n_138), .S
       (n_139));
  DFFHQX1 \result_out_reg[6] (.CK (clk), .D (n_137), .Q
       (result_out[6]));
  OAI2BB1X1 g4523__8428(.A0N (n_136), .A1N (n_135), .B0 (n_102), .Y
       (n_137));
  ADDFX1 g4524__5526(.A (A[6]), .B (n_74), .CI (n_131), .CO (n_134), .S
       (n_135));
  DFFHQX1 \result_out_reg[5] (.CK (clk), .D (n_133), .Q
       (result_out[5]));
  OAI2BB1X1 g4526__6783(.A0N (n_136), .A1N (n_132), .B0 (n_99), .Y
       (n_133));
  ADDFX1 g4527__3680(.A (A[5]), .B (n_85), .CI (n_128), .CO (n_131), .S
       (n_132));
  DFFHQX1 \result_out_reg[4] (.CK (clk), .D (n_130), .Q
       (result_out[4]));
  OAI2BB1X1 g4529__1617(.A0N (n_136), .A1N (n_129), .B0 (n_106), .Y
       (n_130));
  ADDFX1 g4530__2802(.A (A[4]), .B (n_87), .CI (n_125), .CO (n_128), .S
       (n_129));
  DFFHQX1 \result_out_reg[3] (.CK (clk), .D (n_127), .Q
       (result_out[3]));
  OAI2BB1X1 g4532__1705(.A0N (n_136), .A1N (n_126), .B0 (n_103), .Y
       (n_127));
  ADDFX1 g4533__5122(.A (A[3]), .B (n_84), .CI (n_122), .CO (n_125), .S
       (n_126));
  DFFHQX1 \result_out_reg[2] (.CK (clk), .D (n_124), .Q
       (result_out[2]));
  AO21X1 g4535__8246(.A0 (n_136), .A1 (n_123), .B0 (n_117), .Y (n_124));
  ADDFX1 g4536__7098(.A (A[2]), .B (n_71), .CI (n_119), .CO (n_122), .S
       (n_123));
  DFFHQX1 \result_out_reg[1] (.CK (clk), .D (n_121), .Q
       (result_out[1]));
  OAI2BB1X1 g4538__6131(.A0N (n_136), .A1N (n_120), .B0 (n_111), .Y
       (n_121));
  ADDFX1 g4539__1881(.A (A[1]), .B (n_72), .CI (n_113), .CO (n_119), .S
       (n_120));
  DFFHQX1 \result_out_reg[0] (.CK (clk), .D (n_118), .Q
       (result_out[0]));
  OAI2BB1X1 g4541__5115(.A0N (n_136), .A1N (n_114), .B0 (n_116), .Y
       (n_118));
  OAI2BB1X1 g4544__7482(.A0N (n_109), .A1N (n_115), .B0 (n_105), .Y
       (n_117));
  OA21X1 g4545__4733(.A0 (n_110), .A1 (n_115), .B0 (n_94), .Y (n_116));
  ADDFX1 g4542__6161(.A (A[0]), .B (n_70), .CI (n_97), .CO (n_113), .S
       (n_114));
  DFFHQX1 flag_zero_reg(.CK (clk), .D (n_112), .Q (flag_zero));
  NAND2X1 g4546__9315(.A (rst_n), .B (n_107), .Y (n_112));
  OA21X1 g4549__9945(.A0 (n_110), .A1 (n_108), .B0 (n_98), .Y (n_111));
  AO21X1 g4547__2883(.A0 (n_52), .A1 (n_192), .B0 (n_55), .Y (n_115));
  NOR2BX1 g4551__2346(.AN (n_108), .B (n_110), .Y (n_109));
  MX2X1 g4548__1666(.A (n_4), .B (n_82), .S0 (en), .Y (n_107));
  OA21X1 g4560__7410(.A0 (n_80), .A1 (n_104), .B0 (n_76), .Y (n_106));
  OA21X1 g4559__6417(.A0 (n_93), .A1 (n_104), .B0 (n_81), .Y (n_105));
  OA21X1 g4558__5477(.A0 (n_28), .A1 (n_104), .B0 (n_78), .Y (n_103));
  OR4X1 g4561__2398(.A (n_67), .B (n_43), .C (n_51), .D (n_65), .Y
       (n_108));
  OA21X1 g4554__5107(.A0 (n_75), .A1 (n_104), .B0 (n_194), .Y (n_102));
  OA21X1 g4553__6260(.A0 (n_30), .A1 (n_92), .B0 (n_69), .Y (n_101));
  OA21X1 g4557__8428(.A0 (n_77), .A1 (n_104), .B0 (n_195), .Y (n_99));
  AOI21X1 g4555__5526(.A0 (A[0]), .A1 (n_95), .B0 (n_66), .Y (n_98));
  OAI2BB1X1 g4556__6783(.A0N (n_58), .A1N (n_64), .B0 (n_39), .Y
       (n_97));
  AOI22X2 g4572__3680(.A0 (A[6]), .A1 (n_95), .B0 (n_90), .B1
       (result_out[7]), .Y (n_96));
  OA22X1 g4563__1617(.A0 (n_93), .A1 (n_92), .B0 (n_79), .B1 (n_2), .Y
       (n_94));
  NAND2X2 g4567__5122(.A (n_86), .B (n_53), .Y (n_88));
  NAND2X2 g4568__8246(.A (n_86), .B (n_59), .Y (n_87));
  NAND2X2 g4569__7098(.A (n_86), .B (n_57), .Y (n_85));
  NAND2X2 g4570__6131(.A (n_86), .B (n_54), .Y (n_84));
  INVX1 g4562(.A (n_136), .Y (n_83));
  OR4X1 g4550__1881(.A (result_out[3]), .B (result_out[2]), .C
       (result_out[1]), .D (n_196), .Y (n_82));
  OA22X1 g4575__5115(.A0 (n_80), .A1 (n_92), .B0 (n_79), .B1 (n_3), .Y
       (n_81));
  OA22X1 g4576__7482(.A0 (n_77), .A1 (n_92), .B0 (n_79), .B1 (n_0), .Y
       (n_78));
  OA22X1 g4577__4733(.A0 (n_75), .A1 (n_92), .B0 (n_79), .B1 (n_46), .Y
       (n_76));
  XNOR2X1 g4578__6161(.A (n_73), .B (n_48), .Y (n_74));
  XNOR2X1 g4579__9315(.A (n_73), .B (n_45), .Y (n_72));
  XNOR2X1 g4580__9945(.A (n_73), .B (n_50), .Y (n_71));
  XNOR2X1 g4581__2883(.A (n_73), .B (n_44), .Y (n_70));
  AOI22X2 g4573__2346(.A0 (A[7]), .A1 (n_95), .B0 (n_90), .B1
       (flag_carry), .Y (n_69));
  OAI21X1 g4566__1666(.A0 (n_67), .A1 (n_191), .B0 (n_41), .Y (n_68));
  AOI2BB1X4 g4571__7410(.A0N (n_49), .A1N (n_63), .B0 (n_10), .Y
       (n_136));
  AO22X1 g4574__6417(.A0 (A[2]), .A1 (n_193), .B0 (n_90), .B1
       (result_out[1]), .Y (n_66));
  OR4X1 g4586__5477(.A (n_34), .B (n_33), .C (n_36), .D (n_32), .Y
       (n_65));
  AO21X1 g4585__2398(.A0 (op_code[0]), .A1 (flag_carry), .B0 (n_63), .Y
       (n_64));
  MX2X1 g4587__4319(.A (n_58), .B (n_56), .S0 (B[4]), .Y (n_59));
  MX2X1 g4588__8428(.A (n_58), .B (n_56), .S0 (B[5]), .Y (n_57));
  OAI2BB1X1 g4589__5526(.A0N (n_42), .A1N (n_40), .B0 (n_35), .Y
       (n_55));
  MX2X1 g4590__6783(.A (n_58), .B (n_56), .S0 (B[3]), .Y (n_54));
  MX2X1 g4591__3680(.A (n_58), .B (n_56), .S0 (B[7]), .Y (n_53));
  INVX1 g4602(.A (n_51), .Y (n_52));
  OR3X1 g4610__1617(.A (op_code[1]), .B (n_13), .C (n_38), .Y (n_110));
  INVX2 g4593(.A (n_95), .Y (n_104));
  NAND2X1 g4595__2802(.A (B[2]), .B (n_49), .Y (n_50));
  NAND2X1 g4597__1705(.A (B[6]), .B (n_49), .Y (n_48));
  NAND2X1 g4596__8246(.A (B[1]), .B (n_49), .Y (n_45));
  NAND2X1 g4598__7098(.A (B[0]), .B (n_49), .Y (n_44));
  OR2X1 g4607__6131(.A (n_42), .B (n_31), .Y (n_43));
  OA21X1 g4606__1881(.A0 (n_12), .A1 (n_27), .B0 (n_16), .Y (n_41));
  OAI2BB1X2 g4609__5115(.A0N (B[5]), .A1N (n_75), .B0 (n_40), .Y
       (n_51));
  NOR2X4 g4601__7482(.A (n_39), .B (n_38), .Y (n_95));
  OR2X2 g4599__4733(.A (n_49), .B (n_58), .Y (n_86));
  AOI21X1 g4603__9315(.A0 (n_34), .A1 (n_26), .B0 (n_33), .Y (n_35));
  OR4X1 g4604__9945(.A (n_21), .B (n_15), .C (n_11), .D (n_19), .Y
       (n_32));
  AO21X1 g4608__2883(.A0 (op_code[1]), .A1 (n_23), .B0 (n_14), .Y
       (n_63));
  INVX2 g4612(.A (n_58), .Y (n_73));
  OAI21X1 g4613__1666(.A0 (B[0]), .A1 (n_30), .B0 (n_29), .Y (n_31));
  AO21X1 g4620__7410(.A0 (B[2]), .A1 (n_28), .B0 (n_27), .Y (n_67));
  OA21X1 g4619__6417(.A0 (A[6]), .A1 (n_5), .B0 (n_26), .Y (n_40));
  INVX1 g4611(.A (n_24), .Y (n_38));
  AND2X2 g4615__2398(.A (n_23), .B (n_17), .Y (n_49));
  OR2X2 g4616__5107(.A (op_code[0]), .B (n_7), .Y (n_58));
  AO22X1 g4621__6260(.A0 (B[0]), .A1 (n_30), .B0 (B[1]), .B1 (n_93), .Y
       (n_36));
  INVX1 g4631(.A (n_15), .Y (n_16));
  AND3XL g4617__4319(.A (op_code[2]), .B (n_13), .C (n_6), .Y (n_14));
  INVX1 g4632(.A (n_11), .Y (n_12));
  NOR2X2 g4614__8428(.A (n_23), .B (n_10), .Y (n_24));
  INVX2 g4635(.A (n_90), .Y (n_79));
  NOR3X2 g4618__5526(.A (result_out[6]), .B (result_out[0]), .C
       (result_out[7]), .Y (n_9));
  AND2X1 g4637__6783(.A (n_80), .B (B[3]), .Y (n_27));
  NAND2X2 g4625__3680(.A (B[7]), .B (n_8), .Y (n_26));
  NOR2X2 g4628__1617(.A (B[7]), .B (n_8), .Y (n_33));
  NAND2X2 g4638__2802(.A (B[4]), .B (n_77), .Y (n_29));
  NOR2X2 g4639__1705(.A (B[2]), .B (n_28), .Y (n_11));
  NOR2X2 g4641__5122(.A (B[5]), .B (n_75), .Y (n_42));
  INVX1 g4634(.A (n_56), .Y (n_7));
  OR2X1 g4630__8246(.A (op_code[0]), .B (n_6), .Y (n_39));
  NOR2X2 g4627__7098(.A (B[1]), .B (n_93), .Y (n_21));
  NOR2X2 g4624__6131(.A (B[4]), .B (n_77), .Y (n_19));
  OR2X1 g4640__1881(.A (n_13), .B (n_6), .Y (n_17));
  AND2X1 g4626__5115(.A (n_5), .B (A[6]), .Y (n_34));
  NOR2X2 g4636__7482(.A (B[3]), .B (n_80), .Y (n_15));
  AND2X2 g4643__4733(.A (rst_n), .B (n_1), .Y (n_90));
  OR2X2 g4642__6161(.A (op_code[1]), .B (op_code[2]), .Y (n_56));
  NAND2X2 g4629__9315(.A (en), .B (rst_n), .Y (n_10));
  INVX1 g4644(.A (flag_zero), .Y (n_4));
  INVX1 g4647(.A (result_out[4]), .Y (n_46));
  INVX1 g4657(.A (A[7]), .Y (n_8));
  INVX1 g4648(.A (op_code[0]), .Y (n_13));
  INVX1 g4656(.A (op_code[2]), .Y (n_23));
  INVX1 g4652(.A (A[0]), .Y (n_30));
  INVX1 g4649(.A (A[5]), .Y (n_75));
  INVX1 g4651(.A (A[1]), .Y (n_93));
  INVX1 g4645(.A (result_out[2]), .Y (n_3));
  INVX1 g4653(.A (result_out[0]), .Y (n_2));
  INVX1 g4655(.A (en), .Y (n_1));
  INVX1 g4646(.A (result_out[3]), .Y (n_0));
  INVX1 g4654(.A (B[6]), .Y (n_5));
  INVX1 g4658(.A (op_code[1]), .Y (n_6));
  INVX1 g4660(.A (A[2]), .Y (n_28));
  INVX1 g4659(.A (A[3]), .Y (n_80));
  INVX2 g4650(.A (A[4]), .Y (n_77));
  INVX2 drc_bufs4680(.A (n_193), .Y (n_92));
  NOR2BX1 g2(.AN (n_36), .B (n_21), .Y (n_191));
  AO21X1 g4684(.A0 (n_29), .A1 (n_68), .B0 (n_19), .Y (n_192));
  NOR2BX4 g4685(.AN (n_24), .B (n_17), .Y (n_193));
  AOI22X2 g4686(.A0 (n_90), .A1 (result_out[6]), .B0 (n_193), .B1
       (A[7]), .Y (n_194));
  AOI22X2 g4687(.A0 (n_90), .A1 (result_out[5]), .B0 (n_193), .B1
       (A[6]), .Y (n_195));
  NAND3BX2 g4688(.AN (result_out[5]), .B (n_46), .C (n_9), .Y (n_196));
endmodule

