// Generated by Cadence Genus(TM) Synthesis Solution 23.13-s073_1
// Generated on: Mar 26 2026 19:07:44 IST (Mar 26 2026 13:37:44 UTC)

// Verification Directory fv/counter 

module counter(clk, rst, count);
  input clk, rst;
  output [7:0] count;
  wire clk, rst;
  wire [7:0] count;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_7, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_27;
  AOI21X2 g185__2398(.A0 (n_2), .A1 (n_18), .B0 (n_23), .Y (n_24));
  INVX1 g186(.A (n_22), .Y (n_23));
  AOI21X2 g190__5107(.A0 (n_17), .A1 (n_16), .B0 (n_20), .Y (n_21));
  NAND2X2 g187__6260(.A (count[6]), .B (n_20), .Y (n_22));
  AOI21X2 g193__4319(.A0 (n_1), .A1 (n_12), .B0 (n_15), .Y (n_19));
  INVX1 g189(.A (n_20), .Y (n_18));
  NOR2X4 g192__8428(.A (n_17), .B (n_16), .Y (n_20));
  INVX1 g194(.A (n_16), .Y (n_15));
  NAND2X6 g195__5526(.A (count[4]), .B (n_13), .Y (n_16));
  AOI21X2 g198__6783(.A0 (n_11), .A1 (n_10), .B0 (n_13), .Y (n_14));
  INVX1 g197(.A (n_13), .Y (n_12));
  NOR2X6 g200__3680(.A (n_11), .B (n_10), .Y (n_13));
  DFFRHQX4 \count_reg[1] (.RN (rst), .CK (clk), .D (n_27), .Q
       (count[1]));
  AOI21X2 g202__1617(.A0 (n_6), .A1 (n_5), .B0 (n_7), .Y (n_9));
  INVX4 g201(.A (n_7), .Y (n_10));
  NOR2X4 g203__1705(.A (n_6), .B (n_5), .Y (n_7));
  NAND2X8 g208__5122(.A (count[1]), .B (count[0]), .Y (n_5));
  SDFFRX4 \count_reg[7] (.RN (rst), .CK (clk), .D (n_3), .SE (n_22),
       .SI (count[7]), .Q (count[7]), .QN (n_3));
  DFFRX4 \count_reg[3] (.RN (rst), .CK (clk), .D (n_14), .Q (count[3]),
       .QN (n_11));
  DFFRX4 \count_reg[5] (.RN (rst), .CK (clk), .D (n_21), .Q (count[5]),
       .QN (n_17));
  DFFRX4 \count_reg[6] (.RN (rst), .CK (clk), .D (n_24), .Q (count[6]),
       .QN (n_2));
  DFFRX4 \count_reg[4] (.RN (rst), .CK (clk), .D (n_19), .Q (count[4]),
       .QN (n_1));
  DFFRX4 \count_reg[0] (.RN (rst), .CK (clk), .D (n_0), .Q (count[0]),
       .QN (n_0));
  DFFRX4 \count_reg[2] (.RN (rst), .CK (clk), .D (n_9), .Q (count[2]),
       .QN (n_6));
  OA21X4 g2(.A0 (count[1]), .A1 (count[0]), .B0 (n_5), .Y (n_27));
endmodule
